import { OrdersType, ProductType, SellerType, TableData } from "@muc/types";

export const ORDER_RECORD: OrdersType[] = [
  {
    id: 1,
    title: "Total Orders",
    price: 126.5,
    percentage: 34.7,
    date: "oct 20 2023",
  },
  {
    id: 2,
    title: "Active Orders",
    price: 126.5,
    percentage: 34.7,
    date: "oct 20 2023",
  },
  {
    id: 3,
    title: "Completed Orders",
    price: 126.5,
    percentage: 34.7,
    date: "oct 10 2023",
  },
  {
    id: 4,
    title: "Return Orders",
    price: 126.5,
    percentage: 34.7,
    date: "oct 2 2023",
  },
];

export const ORDERS_TABLE_DATA: TableData[] = [
  {
    id: 1,
    poster: "",
    productName: "Nike",
    orderId: 25426,
    date: "Nov 8th, 2023",
    email: "test@gmail.com",
    phoneNumber: 1234567890,
    customerName: "Kavin",
    status: "Delivered",
    product: ["Table", "Toys", "Phone"],
    amount: 200.0,
  },
  {
    id: 2,
    poster: "",
    productName: "Computer",
    orderId: 2542,
    date: "Nov 7th, 2023",
    email: "124test@gmail.com",
    phoneNumber: 1234567890,
    customerName: "Komael",
    product: ["Table", "Toys", "CPU", "Shoes"],
    status: "Canceled",
    amount: 220.0,
  },
  {
    id: 3,
    poster: "",
    productName: "Shoes",
    orderId: 25424,
    date: "Nov 6th, 2023",
    email: "2828@gmail.com",
    phoneNumber: 1234567890,
    customerName: "Nikhil",
    product: ["Table", "Phone"],
    status: "Delivered",
    amount: 20.0,
  },
  {
    id: 4,
    poster: "",
    productName: "Cloths",
    orderId: 255423,
    date: "Nov 5th, 2023",
    email: "124test@gmail.com",
    phoneNumber: 1234567890,
    customerName: "Shivam",
    product: ["Toys", "Phone"],
    status: "Canceled",
    amount: 100.0,
  },
  {
    id: 5,
    poster: "",
    productName: "Socs",
    orderId: 25426,
    date: "Nov 4th, 2023",
    email: "1990test@gmail.com",
    phoneNumber: 1234567890,
    customerName: "Shadab",
    status: "Delivered",
    product: ["Table", "Toys"],
    amount: 500.0,
  },
  {
    id: 6,
    poster: "",
    productName: "Phone",
    orderId: 25421,
    date: "Nov 2nd, 2023",
    email: "asad@gmail.com",
    phoneNumber: 1234567890,
    customerName: "Yogesh",
    product: ["Table", "Toys", "Phone"],
    status: "Delivered",
    amount: 30.0,
  },
];

export const SELLER_DATA: SellerType[] = [
  {
    title: "Modern Lamp",
    price: 850.0,
    sale: 150,
    totalPrice: 1275.0,
  },
  {
    title: "Stylish Chair",
    price: 1200.0,
    sale: 200,
    totalPrice: 2400.0,
  },
  {
    title: "Smart Watch",
    price: 1999.99,
    sale: 300,
    totalPrice: 5999.97,
  },
  {
    title: "Wireless Earbuds",
    price: 1499.0,
    sale: 450,
    totalPrice: "₹6745.50",
  },
  {
    title: "Leather Wallet",
    price: 799.99,
    sale: 500,
    totalPrice: 3999.95,
  },
  {
    title: "Gaming Keyboard",
    price: 2200.5,
    sale: 350,
    totalPrice: 7701.75,
  },
  {
    title: "Bluetooth Speaker",
    price: 1750.0,
    sale: 400,
    totalPrice: 7000.0,
  },
  {
    title: "Fitness Band",
    price: 999.0,
    sale: 600,
    totalPrice: 5994.0,
  },
  {
    title: "Sunglasses",
    price: 1299.0,
    sale: 250,
    totalPrice: 247.5,
  },
  {
    title: "Backpack",
    price: 2150.75,
    sale: 100,
    totalPrice: 2150.75,
  },
];
export const PRODUCTS_DATA: ProductType[] = [
  {
    title: "Router",
    category: "Appliances",
    description:
      "Router is a high-quality product commonly used in various applications.",
    sales: 4382,
    remainingProduct: 321,
    img: "https://via.placeholder.com/150?text=Router",
    price: 99.99,
    paymentMethods: "Master Card",
  },
  {
    title: "Smartphone",
    category: "Accessories",
    description:
      "Smartphone is a high-quality product commonly used in various applications.",
    sales: 4599,
    remainingProduct: 61,
    img: "https://via.placeholder.com/150?text=Smartphone",
    paymentMethods: "Debit Card",
    price: 499.99,
  },
  {
    title: "Keyboard",
    category: "Gadgets",
    description:
      "Keyboard is a high-quality product commonly used in various applications.",
    sales: 3808,
    remainingProduct: 22,
    img: "https://via.placeholder.com/150?text=Keyboard",
    paymentMethods: "Info Card",
    price: 49.99,
  },
  {
    title: "Tablet",
    category: "Gadgets",
    description:
      "Tablet is a high-quality product commonly used in various applications.",
    sales: 1887,
    remainingProduct: 293,
    img: "https://via.placeholder.com/150?text=Tablet",
    paymentMethods: "Master Card",
    price: 299.99,
  },
  {
    title: "Headphones",
    category: "Accessories",
    description:
      "Headphones is a high-quality product commonly used in various applications.",
    sales: 3464,
    remainingProduct: 323,
    img: "https://via.placeholder.com/150?text=Headphones",
    paymentMethods: "Master Card",
    price: 89.99,
  },
  {
    title: "Laptop",
    category: "Gadgets",
    description:
      "Laptop is a high-quality product commonly used in various applications.",
    sales: 3988,
    remainingProduct: 30,
    img: "https://via.placeholder.com/150?text=Laptop",
    paymentMethods: "Master Card",
    price: 799.99,
  },
  {
    title: "Laptop",
    category: "Gadgets",
    description:
      "Laptop is a high-quality product commonly used in various applications.",
    sales: 4564,
    remainingProduct: 370,
    img: "https://via.placeholder.com/150?text=Laptop",
    paymentMethods: "Master Card",
    price: 799.99,
  },
  {
    title: "Tablet",
    category: "Appliances",
    description:
      "Tablet is a high-quality product commonly used in various applications.",
    sales: 2967,
    remainingProduct: 10,
    img: "https://via.placeholder.com/150?text=Tablet",
    paymentMethods: "Master Card",
    price: 349.99,
  },
  {
    title: "Tablet",
    category: "Gadgets",
    description:
      "Tablet is a high-quality product commonly used in various applications.",
    sales: 2096,
    remainingProduct: 169,
    img: "https://via.placeholder.com/150?text=Tablet",
    paymentMethods: "Master Card",
    price: 299.99,
  },
  {
    title: "Keyboard",
    category: "Accessories",
    description:
      "Keyboard is a high-quality product commonly used in various applications.",
    sales: 2863,
    remainingProduct: 360,
    img: "https://via.placeholder.com/150?text=Keyboard",
    paymentMethods: "Master Card",
    price: 49.99,
  },
  {
    title: "Smartphone",
    category: "Gadgets",
    description:
      "Smartphone is a high-quality product commonly used in various applications.",
    sales: 3408,
    remainingProduct: 258,
    img: "https://via.placeholder.com/150?text=Smartphone",
    paymentMethods: "Master Card",
    price: 499.99,
  },
  {
    title: "Smartphone",
    category: "Gadgets",
    description:
      "Smartphone is a high-quality product commonly used in various applications.",
    sales: 3375,
    remainingProduct: 116,
    img: "https://via.placeholder.com/150?text=Smartphone",
    paymentMethods: "Master Card",
    price: 499.99,
  },
  {
    title: "Laptop",
    category: "Accessories",
    description:
      "Laptop is a high-quality product commonly used in various applications.",
    sales: 930,
    remainingProduct: 297,
    img: "https://via.placeholder.com/150?text=Laptop",
    paymentMethods: "Master Card",
    price: 799.99,
  },
  {
    title: "Smartphone",
    category: "Accessories",
    description:
      "Smartphone is a high-quality product commonly used in various applications.",
    sales: 2245,
    remainingProduct: 170,
    img: "https://via.placeholder.com/150?text=Smartphone",
    paymentMethods: "Master Card",
    price: 499.99,
  },
  {
    title: "Battery",
    category: "Accessories",
    description:
      "Battery is a high-quality product commonly used in various applications.",
    sales: 2953,
    remainingProduct: 261,
    img: "https://via.placeholder.com/150?text=Battery",
    paymentMethods: "Master Card",
    price: 29.99,
  },
  {
    title: "Keyboard",
    category: "Accessories",
    description:
      "Keyboard is a high-quality product commonly used in various applications.",
    sales: 2965,
    remainingProduct: 445,
    img: "https://via.placeholder.com/150?text=Keyboard",
    paymentMethods: "Master Card",
    price: 49.99,
  },
  {
    title: "Keyboard",
    category: "Gadgets",
    description:
      "Keyboard is a high-quality product commonly used in various applications.",
    sales: 1409,
    remainingProduct: 205,
    img: "https://via.placeholder.com/150?text=Keyboard",
    paymentMethods: "Master Card",
    price: 49.99,
  },
  {
    title: "Tablet",
    category: "Accessories",
    description:
      "Tablet is a high-quality product commonly used in various applications.",
    sales: 2846,
    remainingProduct: 242,
    img: "https://via.placeholder.com/150?text=Tablet",
    paymentMethods: "Master Card",
    price: 349.99,
  },
  {
    title: "Charger",
    category: "Gadgets",
    description:
      "Charger is a high-quality product commonly used in various applications.",
    sales: 752,
    remainingProduct: 294,
    img: "https://via.placeholder.com/150?text=Charger",
    paymentMethods: "Master Card",
    price: 19.99,
  },
  {
    title: "Headphones",
    category: "Appliances",
    description:
      "Headphones is a high-quality product commonly used in various applications.",
    sales: 3513,
    remainingProduct: 309,
    img: "https://via.placeholder.com/150?text=Headphones",
    paymentMethods: "Master Card",
    price: 89.99,
  },
  {
    title: "Headphones",
    category: "Appliances",
    description:
      "Headphones is a high-quality product commonly used in various applications.",
    sales: 2737,
    remainingProduct: 185,
    img: "https://via.placeholder.com/150?text=Headphones",
    paymentMethods: "Master Card",
    price: 89.99,
  },
  {
    title: "Router",
    category: "Electronics",
    description:
      "Router is a high-quality product commonly used in various applications.",
    sales: 621,
    remainingProduct: 335,
    img: "https://via.placeholder.com/150?text=Router",
    paymentMethods: "Master Card",
    price: 99.99,
  },
  {
    title: "Battery",
    category: "Appliances",
    description:
      "Battery is a high-quality product commonly used in various applications.",
    sales: 2522,
    remainingProduct: 387,
    img: "https://via.placeholder.com/150?text=Battery",
    paymentMethods: "Master Card",
    price: 29.99,
  },
  {
    title: "Battery",
    category: "Appliances",
    description:
      "Battery is a high-quality product commonly used in various applications.",
    sales: 4229,
    remainingProduct: 433,
    img: "https://via.placeholder.com/150?text=Battery",
    paymentMethods: "Master Card",
    price: 29.99,
  },
  {
    title: "Smartphone",
    category: "Appliances",
    description:
      "Smartphone is a high-quality product commonly used in various applications.",
    sales: 1147,
    remainingProduct: 11,
    img: "https://via.placeholder.com/150?text=Smartphone",
    paymentMethods: "Master Card",
    price: 499.99,
  },
  {
    title: "Charger",
    category: "Electronics",
    description:
      "Charger is a high-quality product commonly used in various applications.",
    sales: 4136,
    remainingProduct: 157,
    img: "https://via.placeholder.com/150?text=Charger",
    paymentMethods: "Master Card",
    price: 19.99,
  },
  {
    title: "Headphones",
    category: "Appliances",
    description:
      "Headphones is a high-quality product commonly used in various applications.",
    sales: 4517,
    remainingProduct: 143,
    img: "https://via.placeholder.com/150?text=Headphones",
    paymentMethods: "Master Card",
    price: 89.99,
  },
  {
    title: "Battery",
    category: "Appliances",
    description:
      "Battery is a high-quality product commonly used in various applications.",
    sales: 2244,
    remainingProduct: 316,
    img: "https://via.placeholder.com/150?text=Battery",
    paymentMethods: "Master Card",
    price: 29.99,
  },
  {
    title: "Battery",
    category: "Gadgets",
    description:
      "Battery is a high-quality product commonly used in various applications.",
    sales: 3145,
    remainingProduct: 499,
    img: "https://via.placeholder.com/150?text=Battery",
    paymentMethods: "Master Card",
    price: 29.99,
  },
  {
    title: "Smartphone",
    category: "Gadgets",
    description:
      "Smartphone is a high-quality product commonly used in various applications.",
    sales: 1409,
    remainingProduct: 364,
    img: "https://via.placeholder.com/150?text=Smartphone",
    paymentMethods: "Master Card",
    price: 499.99,
  },
  {
    title: "Tablet",
    category: "Appliances",
    description:
      "Tablet is a high-quality product commonly used in various applications.",
    sales: 450,
    remainingProduct: 381,
    img: "https://via.placeholder.com/150?text=Tablet",
    paymentMethods: "Master Card",
    price: 349.99,
  },
  {
    title: "Charger",
    category: "Gadgets",
    description:
      "Charger is a high-quality product commonly used in various applications.",
    sales: 2363,
    remainingProduct: 109,
    img: "https://via.placeholder.com/150?text=Charger",
    paymentMethods: "Master Card",
    price: 19.99,
  },
  {
    title: "Mouse",
    category: "Accessories",
    description:
      "Mouse is a high-quality product commonly used in various applications.",
    sales: 1769,
    remainingProduct: 230,
    img: "https://via.placeholder.com/150?text=Mouse",
    paymentMethods: "Master Card",
    price: 29.99,
  },
  {
    title: "Monitor",
    category: "Components",
    description:
      "Monitor is a high-quality product commonly used in various applications.",
    sales: 866,
    remainingProduct: 192,
    img: "https://via.placeholder.com/150?text=Monitor",
    paymentMethods: "Master Card",
    price: 179.99,
  },
  {
    title: "Charger",
    category: "Electronics",
    description:
      "Charger is a high-quality product commonly used in various applications.",
    sales: 3902,
    remainingProduct: 59,
    img: "https://via.placeholder.com/150?text=Charger",
    paymentMethods: "Master Card",
    price: 19.99,
  },
  {
    title: "Laptop",
    category: "Electronics",
    description:
      "Laptop is a high-quality product commonly used in various applications.",
    sales: 1630,
    remainingProduct: 163,
    img: "https://via.placeholder.com/150?text=Laptop",
    paymentMethods: "Master Card",
    price: 799.99,
  },
  {
    title: "Monitor",
    category: "Electronics",
    description:
      "Monitor is a high-quality product commonly used in various applications.",
    sales: 2340,
    remainingProduct: 96,
    img: "https://via.placeholder.com/150?text=Monitor",
    paymentMethods: "Master Card",
    price: 179.99,
  },
  {
    title: "Tablet",
    category: "Accessories",
    description:
      "Tablet is a high-quality product commonly used in various applications.",
    sales: 3893,
    remainingProduct: 178,
    img: "https://via.placeholder.com/150?text=Tablet",
    paymentMethods: "Master Card",
    price: 349.99,
  },
  {
    title: "Mouse",
    category: "Gadgets",
    description:
      "Mouse is a high-quality product commonly used in various applications.",
    sales: 2744,
    remainingProduct: 312,
    img: "https://via.placeholder.com/150?text=Mouse",
    paymentMethods: "Master Card",
    price: 29.99,
  },
  {
    title: "Monitor",
    category: "Accessories",
    description:
      "Monitor is a high-quality product commonly used in various applications.",
    sales: 2859,
    remainingProduct: 415,
    img: "https://via.placeholder.com/150?text=Monitor",
    paymentMethods: "Master Card",
    price: 179.99,
  },
  {
    title: "Laptop",
    category: "Appliances",
    description:
      "Laptop is a high-quality product commonly used in various applications.",
    sales: 2845,
    remainingProduct: 111,
    img: "https://via.placeholder.com/150?text=Laptop",
    paymentMethods: "Master Card",
    price: 799.99,
  },
];
